# -----------------------------
# Data Paths
# -----------------------------
data:
  raw_data_path: data/raw/Data.csv
  processed_data_path: data/processed/labeled_dataset.csv

# -----------------------------
# Output
# -----------------------------
output:
  model_path: models/model.pkl